name: test

on:
  push :
    branches : [master]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checks out your repository under $GITHUB WORKSPACE, so your job can access it 
      
        - uses: actions/checkout@v2
      
        - name: Install Node Modules
          run: npm install
        - name: Run Test
          run: npm run test
